# IMPORTING THE LIBRARIES AND DATASETS

In [1]:
import pandas as pd

df = pd.read_csv('amazon_reviews.csv')

df

Unnamed: 0  reviewerName  overall  \
0              0           NaN      4.0   
1              1          0mie      5.0   
2              2           1K3      4.0   
3              3           1m2      5.0   
4              4  2&amp;1/2Men      5.0   
...          ...           ...      ...   
4910        4910        ZM "J"      1.0   
4911        4911            Zo      5.0   
4912        4912     Z S Liske      5.0   
4913        4913      Z Taylor      5.0   
4914        4914           Zza      5.0   

                                             reviewText  reviewTime  day_diff  \
0                                            No issues.  2014-07-23       138   
1     Purchased this for my device, it worked as adv...  2013-10-25       409   
2     it works as expected. I should have sprung for...  2012-12-23       715   
3     This think has worked out great.Had a diff. br...  2013-11-21       382   
4     Bought it with Retail Packaging, arrived legit...  2013-07-13       513   
...                                                 ...         ...       ...   
4910  I bought this Sandisk 16GB Class 10 to use wit...  2013-07-23       503   
4911  Used this for extending the capabilities of my...  2013-08-22       473   
4912  Great card that is very fast and reliable. It ...  2014-03-31       252   
4913  Good amount of space for the stuff I want to d...  2013-09-16       448   
4914  I've heard bad things about this 64gb Micro SD...  2014-02-01       310   

      helpful_yes  helpful_no  total_vote  score_pos_neg_diff  \
0               0           0           0                   0   
1               0           0           0                   0   
2               0           0           0                   0   
3               0           0           0                   0   
4               0           0           0                   0   
...           ...         ...         ...                 ...   
4910            0           0           0                   0   
4911            0           0           0                   0   
4912            0           0           0                   0   
4913            0           0           0                   0   
4914            0           0           0                   0   

      score_average_rating  wilson_lower_bound  
0                      0.0                 0.0  
1                      0.0                 0.0  
2                      0.0                 0.0  
3                      0.0                 0.0  
4                      0.0                 0.0  
...                    ...                 ...  
4910                   0.0                 0.0  
4911                   0.0                 0.0  
4912                   0.0                 0.0  
4913                   0.0                 0.0  
4914                   0.0                 0.0  

[4915 rows x 12 columns]

In [2]:
df.isnull().sum()

Unnamed: 0              0
reviewerName            1
overall                 0
reviewText              1
reviewTime              0
day_diff                0
helpful_yes             0
helpful_no              0
total_vote              0
score_pos_neg_diff      0
score_average_rating    0
wilson_lower_bound      0
dtype: int64

In [3]:
df.dropna()  ##REMOVING THE NULL VALUS

Unnamed: 0  reviewerName  overall  \
1              1          0mie      5.0   
2              2           1K3      4.0   
3              3           1m2      5.0   
4              4  2&amp;1/2Men      5.0   
5              5       2Cents!      5.0   
...          ...           ...      ...   
4910        4910        ZM "J"      1.0   
4911        4911            Zo      5.0   
4912        4912     Z S Liske      5.0   
4913        4913      Z Taylor      5.0   
4914        4914           Zza      5.0   

                                             reviewText  reviewTime  day_diff  \
1     Purchased this for my device, it worked as adv...  2013-10-25       409   
2     it works as expected. I should have sprung for...  2012-12-23       715   
3     This think has worked out great.Had a diff. br...  2013-11-21       382   
4     Bought it with Retail Packaging, arrived legit...  2013-07-13       513   
5     It's mini storage.  It doesn't do anything els...  2013-04-29       588   
...                                                 ...         ...       ...   
4910  I bought this Sandisk 16GB Class 10 to use wit...  2013-07-23       503   
4911  Used this for extending the capabilities of my...  2013-08-22       473   
4912  Great card that is very fast and reliable. It ...  2014-03-31       252   
4913  Good amount of space for the stuff I want to d...  2013-09-16       448   
4914  I've heard bad things about this 64gb Micro SD...  2014-02-01       310   

      helpful_yes  helpful_no  total_vote  score_pos_neg_diff  \
1               0           0           0                   0   
2               0           0           0                   0   
3               0           0           0                   0   
4               0           0           0                   0   
5               0           0           0                   0   
...           ...         ...         ...                 ...   
4910            0           0           0                   0   
4911            0           0           0                   0   
4912            0           0           0                   0   
4913            0           0           0                   0   
4914            0           0           0                   0   

      score_average_rating  wilson_lower_bound  
1                      0.0                 0.0  
2                      0.0                 0.0  
3                      0.0                 0.0  
4                      0.0                 0.0  
5                      0.0                 0.0  
...                    ...                 ...  
4910                   0.0                 0.0  
4911                   0.0                 0.0  
4912                   0.0                 0.0  
4913                   0.0                 0.0  
4914                   0.0                 0.0  

[4913 rows x 12 columns]

In [4]:
df.reset_index(inplace=True)
df

index  Unnamed: 0  reviewerName  overall  \
0         0           0           NaN      4.0   
1         1           1          0mie      5.0   
2         2           2           1K3      4.0   
3         3           3           1m2      5.0   
4         4           4  2&amp;1/2Men      5.0   
...     ...         ...           ...      ...   
4910   4910        4910        ZM "J"      1.0   
4911   4911        4911            Zo      5.0   
4912   4912        4912     Z S Liske      5.0   
4913   4913        4913      Z Taylor      5.0   
4914   4914        4914           Zza      5.0   

                                             reviewText  reviewTime  day_diff  \
0                                            No issues.  2014-07-23       138   
1     Purchased this for my device, it worked as adv...  2013-10-25       409   
2     it works as expected. I should have sprung for...  2012-12-23       715   
3     This think has worked out great.Had a diff. br...  2013-11-21       382   
4     Bought it with Retail Packaging, arrived legit...  2013-07-13       513   
...                                                 ...         ...       ...   
4910  I bought this Sandisk 16GB Class 10 to use wit...  2013-07-23       503   
4911  Used this for extending the capabilities of my...  2013-08-22       473   
4912  Great card that is very fast and reliable. It ...  2014-03-31       252   
4913  Good amount of space for the stuff I want to d...  2013-09-16       448   
4914  I've heard bad things about this 64gb Micro SD...  2014-02-01       310   

      helpful_yes  helpful_no  total_vote  score_pos_neg_diff  \
0               0           0           0                   0   
1               0           0           0                   0   
2               0           0           0                   0   
3               0           0           0                   0   
4               0           0           0                   0   
...           ...         ...         ...                 ...   
4910            0           0           0                   0   
4911            0           0           0                   0   
4912            0           0           0                   0   
4913            0           0           0                   0   
4914            0           0           0                   0   

      score_average_rating  wilson_lower_bound  
0                      0.0                 0.0  
1                      0.0                 0.0  
2                      0.0                 0.0  
3                      0.0                 0.0  
4                      0.0                 0.0  
...                    ...                 ...  
4910                   0.0                 0.0  
4911                   0.0                 0.0  
4912                   0.0                 0.0  
4913                   0.0                 0.0  
4914                   0.0                 0.0  

[4915 rows x 13 columns]

DROPPING THE UNNECCESSARY COLUMNS

In [5]:
df= df.drop(['index','Unnamed: 0','reviewerName','reviewTime','day_diff','helpful_yes','helpful_no','total_vote','score_pos_neg_diff','score_average_rating','wilson_lower_bound'], axis=1)

In [6]:
df

overall                                         reviewText
0         4.0                                         No issues.
1         5.0  Purchased this for my device, it worked as adv...
2         4.0  it works as expected. I should have sprung for...
3         5.0  This think has worked out great.Had a diff. br...
4         5.0  Bought it with Retail Packaging, arrived legit...
...       ...                                                ...
4910      1.0  I bought this Sandisk 16GB Class 10 to use wit...
4911      5.0  Used this for extending the capabilities of my...
4912      5.0  Great card that is very fast and reliable. It ...
4913      5.0  Good amount of space for the stuff I want to d...
4914      5.0  I've heard bad things about this 64gb Micro SD...

[4915 rows x 2 columns]

In [7]:
data = df['reviewText']

In [8]:
data

0                                              No issues.
1       Purchased this for my device, it worked as adv...
2       it works as expected. I should have sprung for...
3       This think has worked out great.Had a diff. br...
4       Bought it with Retail Packaging, arrived legit...
                              ...                        
4910    I bought this Sandisk 16GB Class 10 to use wit...
4911    Used this for extending the capabilities of my...
4912    Great card that is very fast and reliable. It ...
4913    Good amount of space for the stuff I want to d...
4914    I've heard bad things about this 64gb Micro SD...
Name: reviewText, Length: 4915, dtype: object

In [9]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [13]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.stem import WordNetLemmatizer



    
# Initializ INGthe WordNet lemmatizer
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [14]:
## TOKENIZE ,Lemmatize and removing all stopwords
import re

corpus = []
for i in range(0, len(df)):
    processed_review = re.sub('[^a-zA-Z]', ' ',str(df['reviewText'][i]) )
    processed_review = processed_review.lower()
    processed_review = processed_review.split()
    
    
    processed_review =[lemmatizer.lemmatize(word) for word in processed_review if not word in stopwords.words('english')]
    processed_review=' '.join(processed_review)  # Join the lemmatized words back into a single string ##note when you lemittaize word can broken into single words to combine imto list of stings we use this functiom
    corpus.append(processed_review)

In [15]:
corpus

['issue',
 'purchased device worked advertised never much phone memory since download lot stuff brainer',
 'work expected sprung higher capacity think made bit cheesier earlier version paint look clean',
 'think worked great diff bran gb card went south month one held pretty well since note update month zero issue since transferred note note card reliable solid cheer',
 'bought retail packaging arrived legit orange envelope english version asian like picture show arrived quickly bought retail packaging htc one sv lg optimus card working order probably best price get nice sd card',
 'mini storage anything else supposed purchased add additional storage microsoft surface pro tablet come gb supposed sandisk long standing reputation speaks',
 'phone never skip beat file transfer speedy corruption issue memory fade issue would expect sandisk brand great card entrust precious file slightly cheaper piece crap lose everything forgive spending extra couple buck trusted product go good qa',
 'har

In [16]:
#By using SentimentIntensityAnalyzer we can give post,neg,neutal values to our text
from nltk.sentiment import SentimentIntensityAnalyzer

from tqdm.notebook import tqdm

sia=SentimentIntensityAnalyzer()

In [17]:
##adding the corpus into dataset
df['corpus'] = corpus

In [18]:
df

overall                                         reviewText  \
0         4.0                                         No issues.   
1         5.0  Purchased this for my device, it worked as adv...   
2         4.0  it works as expected. I should have sprung for...   
3         5.0  This think has worked out great.Had a diff. br...   
4         5.0  Bought it with Retail Packaging, arrived legit...   
...       ...                                                ...   
4910      1.0  I bought this Sandisk 16GB Class 10 to use wit...   
4911      5.0  Used this for extending the capabilities of my...   
4912      5.0  Great card that is very fast and reliable. It ...   
4913      5.0  Good amount of space for the stuff I want to d...   
4914      5.0  I've heard bad things about this 64gb Micro SD...   

                                                 corpus  
0                                                 issue  
1     purchased device worked advertised never much ...  
2     work expected sprung higher capacity think mad...  
3     think worked great diff bran gb card went sout...  
4     bought retail packaging arrived legit orange e...  
...                                                 ...  
4910  bought sandisk gb class use htc inspire month ...  
4911  used extending capability samsung galaxy note ...  
4912  great card fast reliable come optional adapter...  
4913         good amount space stuff want fit gopro say  
4914  heard bad thing gb micro sd card crapping week...  

[4915 rows x 3 columns]

In [19]:
##polarity_scores 
sia.polarity_scores("The product was not good")

{'neg': 0.376, 'neu': 0.624, 'pos': 0.0, 'compound': -0.3412}

In [20]:
df["corpus"].apply(lambda x: x.upper())   ##for some reference no need to do this


0                                                   ISSUE
1       PURCHASED DEVICE WORKED ADVERTISED NEVER MUCH ...
2       WORK EXPECTED SPRUNG HIGHER CAPACITY THINK MAD...
3       THINK WORKED GREAT DIFF BRAN GB CARD WENT SOUT...
4       BOUGHT RETAIL PACKAGING ARRIVED LEGIT ORANGE E...
                              ...                        
4910    BOUGHT SANDISK GB CLASS USE HTC INSPIRE MONTH ...
4911    USED EXTENDING CAPABILITY SAMSUNG GALAXY NOTE ...
4912    GREAT CARD FAST RELIABLE COME OPTIONAL ADAPTER...
4913           GOOD AMOUNT SPACE STUFF WANT FIT GOPRO SAY
4914    HEARD BAD THING GB MICRO SD CARD CRAPPING WEEK...
Name: corpus, Length: 4915, dtype: object

In [21]:
df["corpus"]

0                                                   issue
1       purchased device worked advertised never much ...
2       work expected sprung higher capacity think mad...
3       think worked great diff bran gb card went sout...
4       bought retail packaging arrived legit orange e...
                              ...                        
4910    bought sandisk gb class use htc inspire month ...
4911    used extending capability samsung galaxy note ...
4912    great card fast reliable come optional adapter...
4913           good amount space stuff want fit gopro say
4914    heard bad thing gb micro sd card crapping week...
Name: corpus, Length: 4915, dtype: object

In [21]:
df["corpus"][0:10].apply(lambda x: sia.polarity_scores(x))

0    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
1    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
2    {'neg': 0.0, 'neu': 0.828, 'pos': 0.172, 'comp...
3    {'neg': 0.0, 'neu': 0.617, 'pos': 0.383, 'comp...
4    {'neg': 0.0, 'neu': 0.759, 'pos': 0.241, 'comp...
5    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
6    {'neg': 0.099, 'neu': 0.589, 'pos': 0.312, 'co...
7    {'neg': 0.087, 'neu': 0.697, 'pos': 0.216, 'co...
8    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
9    {'neg': 0.0, 'neu': 0.457, 'pos': 0.543, 'comp...
Name: corpus, dtype: object

In [22]:
df["corpus"][0:10].apply(lambda x: sia.polarity_scores(x)["compound"])


0    0.0000
1    0.0000
2    0.4019
3    0.9231
4    0.8591
5    0.0000
6    0.8971
7    0.7351
8    0.0000
9    0.9167
Name: corpus, dtype: float64

In [23]:
df["polarity_score"] = df["corpus"].apply(lambda x: sia.polarity_scores(x)["compound"])   ##adding the polarity scorce to the datasets
df.head()

##or
##res={}
# for i ,row in tqdm(df.iterrows(),total=len(df)):
#     text= row['reviewText']
#     myId = row['Unnamed: 0']
#     res[myId] =sia.polarity_scores(text)


overall                                         reviewText  \
0      4.0                                         No issues.   
1      5.0  Purchased this for my device, it worked as adv...   
2      4.0  it works as expected. I should have sprung for...   
3      5.0  This think has worked out great.Had a diff. br...   
4      5.0  Bought it with Retail Packaging, arrived legit...   

                                              corpus  polarity_score  
0                                              issue          0.0000  
1  purchased device worked advertised never much ...          0.0000  
2  work expected sprung higher capacity think mad...          0.4019  
3  think worked great diff bran gb card went sout...          0.9231  
4  bought retail packaging arrived legit orange e...          0.8591

In [22]:
df["corpus"][0:10].apply(lambda x: "pos" if sia.polarity_scores(x)["compound"] > 0 else "neg")

0    neg
1    neg
2    pos
3    pos
4    pos
5    neg
6    pos
7    pos
8    neg
9    pos
Name: corpus, dtype: object

In [23]:
df["sentiment_label"] = df["corpus"].apply(lambda x: "pos" if sia.polarity_scores(x)["compound"] > 0 else "neg")
df.head(20)

overall                                         reviewText  \
0       4.0                                         No issues.   
1       5.0  Purchased this for my device, it worked as adv...   
2       4.0  it works as expected. I should have sprung for...   
3       5.0  This think has worked out great.Had a diff. br...   
4       5.0  Bought it with Retail Packaging, arrived legit...   
5       5.0  It's mini storage.  It doesn't do anything els...   
6       5.0  I have it in my phone and it never skips a bea...   
7       5.0  It's hard to believe how affordable digital ha...   
8       5.0  Works in a HTC Rezound.  Was running short of ...   
9       5.0  in my galaxy s4, super fast card, and am total...   
10      5.0  I like this SD Card because it can take music ...   
11      3.0  It works, but file writes are a bit slower tha...   
12      5.0      THE NAME OF ITSELF SPEAKS OUT. GO SANDISK GO!   
13      5.0  Solid SDHC card that is fast (at reading and w...   
14      5.0  Heard that the card's write speed is insuffici...   
15      5.0  I bought this to use with my go pro hero 3 bla...   
16      5.0  got this because i had a 2 GB one that filled ...   
17      5.0  Class 10 Speed Rating for Seamless Full HD Vid...   
18      5.0  The read and write speeds are better than the ...   
19      5.0  This works with the NL1520.  No video stutteri...   

                                               corpus sentiment_label  
0                                               issue             neg  
1   purchased device worked advertised never much ...             neg  
2   work expected sprung higher capacity think mad...             pos  
3   think worked great diff bran gb card went sout...             pos  
4   bought retail packaging arrived legit orange e...             pos  
5   mini storage anything else supposed purchased ...             neg  
6   phone never skip beat file transfer speedy cor...             pos  
7   hard believe affordable digital become gb devi...             pos  
8   work htc rezound running short space gb sandis...             neg  
9   galaxy super fast card totally happy happy sti...             pos  
10  like sd card take music video downloads person...             pos  
11  work file writes bit slower expected usb reade...             neg  
12                          name speaks go sandisk go             neg  
13  solid sdhc card fast reading writing fast reco...             pos  
14  heard card write speed insufficient however us...             neg  
15  bought use go pro hero black edition requires ...             pos  
16  got gb one filled kept getting insufficient di...             pos  
17  class speed rating seamless full hd videothe s...             pos  
18  read write speed better samsung sd card previo...             pos  
19  work nl video stuttering like gb blah blah bla...             neg

In [24]:
df["sentiment_label"].value_counts()

pos    3939
neg     976
Name: sentiment_label, dtype: int64

In [25]:
from sklearn.preprocessing import LabelEncoder
df["sentiment_label"] = LabelEncoder().fit_transform(df["sentiment_label"])

X = df["corpus"]
y = df["sentiment_label"]

In [26]:
X

0                                                   issue
1       purchased device worked advertised never much ...
2       work expected sprung higher capacity think mad...
3       think worked great diff bran gb card went sout...
4       bought retail packaging arrived legit orange e...
                              ...                        
4910    bought sandisk gb class use htc inspire month ...
4911    used extending capability samsung galaxy note ...
4912    great card fast reliable come optional adapter...
4913           good amount space stuff want fit gopro say
4914    heard bad thing gb micro sd card crapping week...
Name: corpus, Length: 4915, dtype: object

In [29]:
y

0       0
1       0
2       1
3       1
4       1
       ..
4910    1
4911    1
4912    1
4913    1
4914    1
Name: sentiment_label, Length: 4915, dtype: int32

In [27]:
pip install textblob


Note: you may need to restart the kernel to use updated packages.


# VECTORS

In [31]:
from textblob import TextBlob         ##taking a sample text and doing bag of words 

a = "This is a sample sentence."

blob = TextBlob(a)
ngrams = blob.ngrams(3)  ##ngrams means splitting the data into 3 

print(ngrams)


[WordList(['This', 'is', 'a']), WordList(['is', 'a', 'sample']), WordList(['a', 'sample', 'sentence'])]


In [30]:
from sklearn.feature_extraction.text import CountVectorizer   ##again taking the sampke data & doing CountVectorizer

cor = ['This is my pen.',
          'This document is our company document.',
          'And this is the  pen which i brought it for you',
          'Is this ,your pen?']

In [31]:
vectorizer = CountVectorizer()
X_c = vectorizer.fit_transform(cor)
vectorizer.get_feature_names_out()
print(vectorizer.get_feature_names_out())
X_c.toarray()

['and' 'brought' 'company' 'document' 'for' 'is' 'it' 'my' 'our' 'pen'
 'the' 'this' 'which' 'you' 'your']


array([[0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 2, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1]], dtype=int64)

In [32]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X_n = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()
print(vectorizer2.get_feature_names_out())
X_n.toarray()



##i try to use countvectorizer but is not giving proper vectors

['aa well' 'aac format' 'aacute mare' ... 'zune music' 'zune way'
 'zunehd next']


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
vectorizer = CountVectorizer()
X_count = vectorizer.fit_transform(X)

vectorizer.get_feature_names_out()[10:15]
X_count.toarray()[10:15]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# TFIDF VECTOR

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(analyzer='word')
X_w = vectorizer.fit_transform(cor)
vectorizer.get_feature_names_out()
X_w.toarray()

##i try to use TFIDF vector method using that sample text

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37350242, 0.        , 0.71573922, 0.        , 0.45684708,
        0.        , 0.37350242, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.39089239, 0.78178478, 0.        ,
        0.20398387, 0.        , 0.        , 0.39089239, 0.        ,
        0.        , 0.20398387, 0.        , 0.        , 0.        ],
       [0.35461779, 0.35461779, 0.        , 0.        , 0.35461779,
        0.18505427, 0.35461779, 0.        , 0.        , 0.22634794,
        0.35461779, 0.18505427, 0.35461779, 0.35461779, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37350242, 0.        , 0.        , 0.        , 0.45684708,
        0.        , 0.37350242, 0.        , 0.        , 0.71573922]])

In [38]:
tf_idf = TfidfVectorizer()
X_tf = tf_idf.fit_transform(X)
print(tf_idf.get_feature_names_out())
X_tf.toarray()

['aa' 'aaaaaaaa' 'aac' ... 'zumo' 'zune' 'zunehd']


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [36]:
X_tf[0]

<1x6778 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

# MODEL BUILDING

In [43]:
from sklearn.model_selection import train_test_split

# Assuming you have your data in 'X' (features) and 'y' (labels)
X_train, X_test, y_train, y_test = train_test_split(X_tf, y, test_size=0.3, random_state=42)

In [44]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

logreg.fit(X_train,y_train)

LogisticRegression()

In [45]:
sample_data = pd.Series("it was good but I am sure that it fits me")

In [46]:
sample_data= CountVectorizer().fit(X).transform(sample_data)

In [47]:
sample_data

<1x6778 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [48]:
y_test

2346    1
4344    1
691     0
3910    0
2487    1
       ..
3447    1
2218    0
682     1
3231    1
3121    1
Name: sentiment_label, Length: 1475, dtype: int32

In [50]:
y_pred=logreg.predict(X_test)

In [51]:
y_pred[:40]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [52]:
from sklearn.metrics import accuracy_score

In [53]:
accuracy = accuracy_score(y_test, y_pred)

In [54]:
accuracy

0.8149152542372882

In [55]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.15      0.26       317
           1       0.81      1.00      0.89      1158

    accuracy                           0.81      1475
   macro avg       0.87      0.57      0.58      1475
weighted avg       0.84      0.81      0.76      1475

